name: Bug report
description: Create a report to help us improve
body:
- type: markdown
  attributes:
    value: Please note we will close your issue without comment if you do not fill out the requested information.
- type: checkboxes
  attributes:
    label: Ensure the following before filing this issue
    options:
    - label: |
        I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))
      required: true
    - label: |
        I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
        and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)
      required: true
    # - label: |
    #     If the issue happens on JRuby or TruffleRuby, and does not happen on CRuby (please check), file an issue there instead. It's very unlikely ruby/setup-ruby is the cause.
    #   required: true
- type: dropdown
  attributes:
    label: Are you running on a GitHub-hosted runner or a self-hosted runner?
    options:
      - GitHub-hosted runner
      - self-hosted runner
  validations:
    required: true
- type: textarea
  attributes:
    render: yaml
    label: The workflow code or a link to the workflow file
  validations:
    required: true
- type: input
  attributes:
    label: Link to the log of a failed workflow job, or to a gist with the output
  validations:
    required: true
- type: textarea
  attributes:
    render: shell
    label: The command and output of the failing step
  validations:
    required: true
- type: textarea
  attributes:
    label: Any other notes?
  validations:
    required: false
